### PR TITLE
Correct a wrong word in async_sgd_design.md

### PR DESCRIPTION
**Pull request by shijungg**
Correct a wrong word in async_sgd_design.md

### CODE REVIEW

**Review by mhaoli — APPROVED** [review]
Thanks!

**Comment by mhaoli** [comment]
In this PR, there are 5 commits. Only the last commit is related to this PR. You'd better sync your local git repo to the head of the ElasticDL repo and add the change. In this way, there would be only 1 commit.

**Review by terrytangyuan — APPROVED** [review]

**Comment by terrytangyuan** [comment]
We only allow squash merge so multiple commits should be fine. But @LiMinghao1994 is right, @shijungg you should probably rebase/update your local branch before making new commits.

**Comment by shijungg** [comment]
@LiMinghao1994 @terrytangyuan I'm sorry about it. Thanks for your advice. I will take note of it.

**Pull request merged**
