### PR TITLE
Remove the out-of-date design doc and link.

### PR DESCRIPTION
**Pull request by brightcoder01**

### CODE REVIEW

**Review by workingloong — DISMISSED** [review]
LGTM

**Review by terrytangyuan — CHANGES_REQUESTED** [review]
Move to archived instead of deleting it? https://github.com/sql-machine-learning/elasticdl/tree/develop/docs/designs/archived

**Review by terrytangyuan — COMMENTED** [review]
https://github.com/sql-machine-learning/elasticdl/tree/develop/docs/designs/archived

**Comment by brightcoder01** [comment]
> Move to archived instead of deleting it? https://github.com/sql-machine-learning/elasticdl/tree/develop/docs/designs/archived

Good idea, updated.

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
